/* Calculate a new variable called PROFIT*/
DATA WORK.CARS;
  SET SASHELP.CARS;
  PROFIT = MSRP - INVOICE;
RUNS;


/* Calculate a new variable called CLASS */
/* IF ELSE statement */
DATA WORK.CARS;
  SET SASHELP.CARS;
  IF MSRP > 45000 THEN CLASS = "LUXURY";
  ELSE CLASS = "NOT LUXURY";
  PROFIT = MSRP - INVOICE;
RUNS;


/* DO statement */
/* CAT statement to concatenate */
DATA WORK.CARS;
  SET SASHELP.CARS;
  IF MSRP > 45000 THEN DO;
  CLASS = "LUXURY";
  PRICE = "HIGH";
  END;
  ELSE DO;
  CLASS = "NOT LUXURY";
  PRICE = "LOW";
  END;
  UNIQUECARBRAND = CATX("-",MAKE,MODEL);
  IF UPCASE(ORIGIN) = "EUROPE" THEN DO;
  SALES_TAX = MSRP * 0.0825;
  LUXURY_TAX = (MSRP - 45000) * 0.025;
  END;
  PROFIT = MSRP - INVOICE;
  FINAL_PROFIT = PROFIT - SALES_TAX - LUXURY_TAX;
RUNS;
