/*  Use WHERE in PROC, use IF for all the others*/
DATA WORK.EUROCARS;
SET SASHELP.CARS;
WHERE UPCASE(ORIGIN) = "EUROPE";
RUNS;

DATA WORK.EUROCARS;
SET SASHELP.CARS;
PROFIT = MSRP - INVOICE;
IF PROFIT > 5000; /* using WHERE will get error */
RUNS;


DATA WORK.EUROCARS;
SET SASHELP.CARS;
PROFIT = MSRP - INVOICE;
RUNS;

PROC PRINT DATA = WORK.EUROCARS;
WHERE PROFIT < 5000;
RUN;
