/* Format, Label, Split PROC Format */
TITLE "The first five observations out of 322";
	PROC PRINT DATA = SASHELP.BASEBALL(OBS = 5) NOOBS;
RUN;

PROC PRINT DATA = SASHELP.BASEBALL(OBS = 5) NOOBS;
	FORMAT SALARY COMMA9.2;
RUN;

PROC PRINT DATA = SASHELP.BASEBALL(OBS = 5) NOOBS;
	FORMAT SALARY DOLLAR9.2 NAME$4.;
RUN;

/* Format: Date */
TITLE "SASHELP.BUY";
	PROC PRINT DATA = SASHELP.BUY(OBS = 5) NOOBS;
RUN;

TITLE "SASHELP.BUY";
	PROC PRINT DATA = SASHELP.BUY(OBS = 5) NOOBS;
	FORMAT DATE DATE9.;
RUN;

TITLE "SASHELP.BUY";
	PROC PRINT DATA = SASHELP.BUY(OBS = 5) NOOBS;
	FORMAT DATE DATE6.;
RUN;

TITLE "SASHELP.BUY";
	PROC PRINT DATA = SASHELP.BUY(OBS = 5) NOOBS;
	FORMAT DATE DDMMYY8.;
RUN;

TITLE "SASHELP.BUY";
	PROC PRINT DATA = SASHELP.BUY(OBS = 5) NOOBS;
	FORMAT DATE DDMMYY10.;
RUN;


/* Label */
TITLE "The first five observations out of 322";
	PROC PRINT DATA = SASHELP.BASEBALL(OBS = 5) NOOBS;
RUN;

DATA WORK.BASEBALL;
	SET SASHELP.BASEBALL;
	LABEL
	NAME = "Last Name, First Name";
RUN;

PROC CONTENTS DATA = WORK.BASEBALL;
RUN;

DATA WORK.BASEBALL;
SET SASHELP.BASEBALL;
LABEL
Name = "Last Name, First Name";
RUN;

PROC CONTENTS DATA = SASHELP.BASEBALL;
RUN;

TITLE "The first five observations out of 322";
	PROC PRINT DATA = SASHELP.BASEBALL(OBS = 5) NOOBS LABEL;
RUN;

TITLE "The first five observations out of 322";
	PROC PRINT DATA = WORK.BASEBALL(OBS = 5) NOOBS LABEL;
RUN;

/* Split */
PROC PRINT DATA = SASHELP.BASEBALL LABEL;
  FORMAT NAME $4.;
  LABEL
  NAME = "Last Name, First Name";
RUN;

PROC PRINT DATA = SASHELP.BASEBALL(OBS = 5) NOOBS LABEL SPLT = "*";
	FORMAT NAME $4.;
	LABEL
	NAME = "Last Name, Fir*st Name";
RUN;

/* PROCD FORMAT */
PROC FORMAT;
	VALUE SALARYRANGE 0-<200 = "SALARY1"
	200-<400 = "SALARY2"
	400-<600 = "SALARY3";
RUN;

PROC PRINT DATA = WORK.BASEBALL(OBS=5) NOOBS;
	FORMAT SALARY SALARYRANGE.;
RUN;
