/* Calculate a new variable called PROFIT*/
DATA WORK.CARS;
SET SASHELP.CARS;
PROFIT = MSRP - INVOICE;
RUNS;


/* Calculate a new variable called CLASS*/
/* IF ELSE statement/
DATA WORK.CARS;
SET SASHELP.CARS;
IF MSRP > 45000 THEN CLASS = "LUXURY";
ELSE CLASS = "NOT LUXURY";
PROFIT = MSRP - INVOICE;
RUNS;


/* DO statement */
/* CAT statement to concatenate*/
DATA WORK.CARS;
SET SASHELP.CARS;
IF MSRP > 45000 THEN DO;
CLASS = "LUXURY"
PRICE = "HIGH";
END;
ELSE DO;
CLASS = "NOT LUXURY";
PRICE = "LOW";
END;
UNIQUE-CAR = CATX("|",MAKE,MODEL);
IF UPCASE(ORIGIN) = "EUROPE" THEN DO;
SALES_TAXES = MSRP * 0.10;
LUXURY_TAXES = (MSRP - 45000) * 0.025;
END;
PROFIT = MSRP - INVOICE;
FINAL_PROFIT = PROFIT - SALES_TAXES - LUXURY_TAXES;
RUNS;
